### PR TITLE
Feature: Module for monkeypatching the builtin functions

### PR DESCRIPTION
**Pull request by binaryDiv**
This PR makes the integration of snekoil into existing projects easier by adding the module `snekoil.monkeypatch`, which replaces the builtin/standard library functions `range` and `time.sleep` with the much more efficient functions provided by the library.

Now you don't have to remember to import the optimized functions from the library anymore, just insert an `import snekoil.monkeypatch` at the very start of your application (make sure to import this before anything else), and all calls to `range` and `time.sleep` will be automatically replaced with calls to their snekoil equivalents.

Not only does this reduce the amount of typing, it also has the side effect of optimizing the code of all the libraries that your project depends on.

Additionally to `snekoil.monkeypatch` there is the counterpart `snekoil.unmonkeypatch`, which reverses the monkeypatching, so that the original functions are used again. Of course, in reality there is no real reason why you would want to go back to the slow original functions. The purpose if the `unmonkeypatch` module is mainly for testing purposes: The unit tests for the monkeypatch module need to undo the monkeypatching again, otherwise the unit tests that compare the snekoil functions with the originals would fail.

### CODE REVIEW

**Comment by ninanomenon** [comment]
I propose to call the monkeypatch functions, snekpatch.

**Comment by ninanomenon** [comment]
And i think we should merge #4 first

**Review by sigmasternchen — APPROVED** [review]
lgtm

**Comment by binaryDiv** [comment]
> I propose to call the monkeypatch functions, snekpatch.

That's good! I'll change it (and then rebase) :3

**Comment by binaryDiv** [comment]
Rebased and renamed!

**Comment by binaryDiv** [comment]
(Whoops - fixed a bug in the unit tests :upside_down_face: )

**Comment by ninanomenon** [comment]
Thanks to you @binaryDiv :D

**Comment by ninanomenon** [comment]
@overflowerror i think there is still an error with the commit pipeline

**Comment by sigmasternchen** [comment]
@l1f Weird. I'll take a look later. But since the commit messages look fine, let's ignore it for now.

**Pull request merged**
